# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests in node 18
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js 18.x Jest coverage report

on:
  pull_request:
    branches: [ "master" ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ArtiomTr/jest-coverage-report-action@v2
    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
          node-version: '18.x'
          cache: 'npm'
          test-script: npm test
    - run: npm ci
